import pygame
import random

#Screen/Game Parameters
WIDTH = 500
HEIGHT = 500
FPS = 30

# Tilemap Parameters
GRASS = (85, 125, 70)
DIRT = (153, 76, 10)
MAPWIDTH = 25
MAPHEIGHT = 25
TILESIZE = 20

tilemap = [
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 					[GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS, GRASS, GRASS, GRASS, DIRT, GRASS],
	 				]

# initialize pygame and create window
pygame.init()
pygame.mixer.init()
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Python Tower Defense")

def drawMap(mapWidth, mapHeight):
	for row in range(MAPWIDTH):
	   for col in range(MAPHEIGHT):
	   	pygame.draw.rect(screen, tilemap[row][col], (row*TILESIZE,col*TILESIZE, TILESIZE, TILESIZE))	


# game loop
running = True
while running: 
	# Process input (events)
	for event in pygame.event.get():
		if event.type == pygame.QUIT:
			running = False
	# Update
  
	# Draw / render
		# Draw Map
	drawMap(MAPWIDTH, MAPHEIGHT)

	# after drawing everything, flip the display
	pygame.display.flip()





##### QUIT GAME 
pygame.quit()